### ISSUE TITLE
Is it possible to provide a savepoint of the model to test the effect?

### ISSUE THREAD

**Issue by 980202006** [Tengfei-Wang/Implicit-Internal-Video-Inpainting#18]
I do some tests on the model, is it possible to provide a savepoint of the model?Thanks.

**Comment by Tengfei-Wang** [comment]
The model is trained from scratch for each sequence, and there is no need for the save point. If you just need our results on DAVIS sequences, you can find them on the provided one drive link.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: 980202006 ***@***.***>
发送时间: Monday, July 4, 2022 3:51:58 PM
收件人: Tengfei-Wang/Implicit-Internal-Video-Inpainting ***@***.***>
抄送: Subscribed ***@***.***>
主题: [Tengfei-Wang/Implicit-Internal-Video-Inpainting] Is it possible to provide a savepoint of the model to test the effect? (Issue #18)


I do some tests on the model, is it possible to provide a savepoint of the model?Thanks.

―

**Comment by 980202006** [comment]
Thank you!
