### ISSUE TITLE
 About the pipeline

### ISSUE THREAD

**Issue by sydney0zq** [Tengfei-Wang/Implicit-Internal-Video-Inpainting#2]
Hi, thanks for your released code.

It takes too long to train&test a video, will it possible to fastly test any input? The example "bmx-trees" takes several hours to finish.

Thanks.

**Comment by Tengfei-Wang** [comment]
Hi,  during the training, you can use Tensorboard to watch the training process (and logged results), and early-stop when the results are satisfactory. In our experiment, "BMX-trees" takes ~20,000 iterations (~2 hours) to converge with a single GPU.  To accelerate the training, multi-GPUs may be used.
BTW,  we put our results of 70 videos from DAVIS in https://hkustconnect-my.sharepoint.com/:f:/g/personal/tfwang_connect_ust_hk/EmtOPEAarqdFj4yDLECg2oABsylzC4lKjuFyyg7o2TTdyQ. If you want our results on DAVIS for reference,  you can easily download them without training :)

**Comment by sydney0zq** [comment]
@Tengfei-Wang I will check the code and results. Thanks for your reply and suggestion.

**Comment by sydney0zq** [comment]
Another question when will the model for 4k videos be released? I want to test them on some real videos.
Could you please send a copy of rough code to me，I want to read and try to run it? My email is theodoruszq@gmail.com.

Thanks in advance!

**Comment by Tengfei-Wang** [comment]
Hi,   the code for 4K videos is expected to be released in about two weeks.  You can refer to 'RefineModelUp' in model.py and 'build_dataset_up' in dataloader.py for the model and data loader used for the progressive training.

**Comment by sydney0zq** [comment]
Thanks for your reply.

**Comment by BarnabasTakacs** [comment]
Hello,

Great work. I wold also like to test the 4K pipeline. Could you provide a sample or some hints on how long it took to train?
Thank you inadvance.
Barnabas
