### ISSUE TITLE
What "Mask Propagation from A Single Frame" usage?

### ISSUE THREAD

**Issue by Vadim2S** [Tengfei-Wang/Implicit-Internal-Video-Inpainting#5]
1) How much annotation files I am must provide?
2) Must I am provide corresponding mask for them or not?
3) Why annotation pictures red and green and what difference?
4) How much frames I am must provide for video?
5) Is video must be without fast object movement?

**Comment by ken-ouyang** [comment]
1. Usually one frame but more frames can be better. 
2. Yes. At least one frame.
3. The annotation is from Davis Dataset which means different object. But we will turn it into black and white when using it.
4. Do you mean how many frames you need for training? We do it on one frame but more frames can be better. 
5. I have not tried videos with fast object movement. I guess it will fail in those cases. 

BTW, mask propagation is a simple extension of the method so it may not outperform SOTA structures. You can also try those methods for getting the masks.
