### ISSUE TITLE
About test

### ISSUE THREAD

**Issue by lixixin** [Tengfei-Wang/Implicit-Internal-Video-Inpainting#6]
Hi, I‘m a little confused about this method.
If I want to test 10 different videos, should I train 10 different models? and every model needs about 4 hours?
or just need to train a model which can be applied to other videos?

**Comment by Tengfei-Wang** [comment]
You need to train 10 models in this case. This is the main limitation of the internal learning methods. Multi-GPUs can help accelerate the training.
